### ISSUE TITLE
Advanced filtering doesn't work on the Custom Chart when type = test cases

### ISSUE THREAD

**Issue by anagram15** [RallyCommunity/CustomChart#47] opened 2018-06-07 17:10 UTC
Steps to Repro:

1. Log into Agile Central
2. Add the Custom Chart app to a custom page
3. Edit the App Settings to be for Type "Test Case"  and Save
4. Click on the Filter icon - notice nothing happens

Tested with several other work item types and test case seems to be the only one with this issue.

**Comment by sherimoore** [comment] 2018-06-07 20:01
Hi @anagram15 I just tried to re-produce this and had no issues, my test cases showed up in the chart.  Did you confirm that the project you are looking at has test cases?

**Comment by krmorse** [comment] 2018-06-07 20:15
This is a weird one.  The easiest way to repro is to add a new app that has never been configured before and set it to test cases.  The problem is with the default quick filters, and test cases not having a schedule state field.  It should be fixed in #48

**Closed** 2018-06-08 14:39 UTC
